#!/bin/bash
#PBS -N output          
#PBS -l walltime=03:00:00          
#PBS -l select=1:ncpus=2:mem=8gb:ngpus=1

source ~/miniforge3/etc/profile.d/conda.sh
conda activate iso

cd $PBS_O_WORKDIR

echo "JOB STARTED AT $(date)"
python -u /rds/general/user/ns1324/home/iso/scripts/main.py --model_path Qwen/Qwen2.5-VL-3B-Instruct --model_name Qwen2_5VL_3B --prompt_version v1 --prompt_position none --batch_size 4 --max_new_tokens 1024 --seed 13 --output_dir /rds/general/user/ns1324/home/iso/results/13_02_2026/Qwen2_5VL-3B/Baseline 

